### ISSUE TITLE
Running make will delete ~/bin

### ISSUE THREAD

**Issue by yonran** [dylanmtaylor/LibreScribe#39]
If you run what seems to be the logical steps to compile LibreScribe, then it will delete the bin subdirectory in your home directory. Kind of annoying because ~/bin happened to be where I put some useful scripts.

```
./generate-makefile.sh
make
```

**Comment by robmyers** [comment]
This bug just deleted a big chunk of my ~/bin directory before I could press ctrl-c.

Including my backup and restore scripts. :-D

**Comment by dylanmtaylor** [comment]
Fixed in latest.
