### ISSUE TITLE
Smartpen::getName returns with invalid pointer

### ISSUE THREAD

**Issue by johndrinkwater** [dylanmtaylor/LibreScribe#42]
Noticed in terminal output, along with missing device name in the UI,
```
device name (hex): 46657272617269353939
From HEX: Ferrari599
���}
device name label set, setting battery gauge value
```

Fixed it with a strdup, but know that is imperfect https://github.com/johndrinkwater/LibreScribe/commit/8d0d02cd56eda709e1dda79727343d714fa475a3

**Comment by dylanmtaylor** [comment]
Pulled in this change. Closing.
